# Uncomment the following to deploy this app as a static site on render
services:
- type: web
  name: next-js
  runtime: node
  plan: starter
  buildCommand: yarn; yarn build
  startCommand: yarn start
  autoDeploy: false
  envVars:
  - key: NODE_ENV
    value: production